### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by nuxwin** [piwik/piwik-log-analytics#102]
Hello ;

Right now, when one want install Piwik via composer, there is no way to require the piwik project submodules (such as this one) through composer.

In my composer root file, I would be able to:

Require piwik (already possible)
Require this piwik-log-analytics submodule (as another composer package)

QUESTION:

At this moment, what is the exact purpose of piwik composer package?

**Comment by mattab** [comment]
Hi there,

we don't really support "installing full Piwik via composer", although it's possible to install Piwik  via composer, but it won't work well because it's missing log analytics folder and also missing the required `PiwikTracker` folder here: https://github.com/piwik/piwik/tree/master/libs.

> At this moment, what is the exact purpose of piwik composer package?

What do you mean?
