### ISSUE TITLE
test log importer against different versions of Piwik (both python tests + PHP System test)

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik-log-analytics#54]
We should test the log importer using the python tests in one build, then in several other builds (1 per supported Piwik version), that ImportLogsTest.php works correctly.

If we add the log importer build to the weekly restart, we could perhaps disable the ImportLogsTest on the main build. We can't move it though, because if we can't define one test for all Piwik versions.

I'd like to add builds for Piwik 2.0 => current version.

**Comment by mattab** [comment]
What's the value in testing each piwik version? I think it's enough to test the latest version, since  the import log calls the [Tracking API](http://developer.piwik.org/api-reference/tracking-api) and this API should be tested in piwik/piwik

Also I think the importsLogs test should stay in piwik/piwik SystemTests CI job, because this repository only cares about the python script and trusts that the API will work well.

**Comment by diosmosis** [comment]
The script, as is, won't work with older versions of piwik. We should make it work and then add tests so it won't break again, no?

**Comment by halfdan** [comment]
IMHO it would be enough for the log importer to support the last two versions of Piwik to allow for faster development. Otherwise I agree with @mattab that the tests should remain in piwik/piwik and this script should be tested to properly make API requests (but that can be stubbed and doesn't need a running Piwik instance).

**Comment by diosmosis** [comment]
A stubbed API wouldn't catch the error that occurs w/ older Piwiks, and I think there are many clients that want to use new importer features w/ older Piwik's (I've noticed 2.4 & 2.7 in emails, and an unspecified version in an issue).

**Comment by mattab** [comment]
> The script, as is, won't work with older versions of piwik.

Do you have an or more  example of when the script won't work with older Piwik?

**Comment by diosmosis** [comment]
I only have one, if you run w/ an older Piwik, the request will have: format=JSON2. For some older Piwiks, this will be an unknown format (it was introduced to fix a bug in the normal JSON format). Fairly quick fix, but w/o tests against an actual Piwik, we won't know when we inadvertently break the script for old Piwik versions.

**Comment by mattab** [comment]
Good point with JSON2... I think it's definitely an exception and we should not introduce breaking changes like this in the future in the Piwik API. To fix this issue I edited readme and noted that the script requires Piwik 2.6.0+ where this json2 format was introduced. I'm closing this issue as this repo should only test the python script and the API requests created but not test Piwik itself.
